version: "3"

networks:
  local:

services:
  db:
    image: postgres
    networks:
      - local
    ports:
      - ${DB_PORT}:${DB_INTERNAL_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  apiserver:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
      args:
        - APP_NAME=apiserver
    networks:
      - local
    ports:
      - ${API_SERVER_BIND_ADDR}:${API_SERVER_BIND_INTERNAL_ADDR}
    depends_on:
      - db

  dailybot:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
      args:
        - APP_NAME=dailybot
    networks:
      - local
    ports:
      - ${DAILY_BOT_SERVER_BIND_ADDR}:${DAILY_BOT_SERVER_BIND_INTERNAL_ADDR}
    depends_on:
      - db