version: "3"

networks:
  local:

services:
  db:
    image: postgres
    env_file:
      - .env
    networks:
      - local
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
