version: "3"

networks:
  local:

services:
  db:
    image: postgres
    env_file:
      - .env
    networks:
      - local
    ports:
      - ${DB_PORT}:${DB_INTERNAL_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  bot:
    build:
      context: ../
      dockerfile: docker/go/Dockerfile
      args:
        - APP_NAME=bot
    env_file:
      - .env
    networks:
      - local
    ports:
      - ${SERVER_BIND_ADDR}:${SERVER_INTERNAL_BIND_ADDR}
    depends_on:
      - db